# Section title
# about_title: About Me (Use this to override)
# projects_title: Projects #(Use this to override)
# experiences_title: Work experience #(Use this to override)
# educations_title: Education #(Use this to override)
# hobbies_title: Activities and interests #(Use this to override)
